DECLARE @M INT , @F INT
SET @M = (SELECT COUNT(SEXO) FROM FUNCIONARIO WHERE SEXO = 'M')
SET @F = (SELECT COUNT(SEXO) FROM FUNCIONARIO WHERE SEXO = 'F')

IF (@M < @F)
	PRINT 'EXISTEM MAIS MULHERES QUE HOMENS NA EMPRESA'
ELSE 
	IF (@M > @F)
		PRINT'EXISTEM MAIS HOMENS QUE MULHERES NA EMPRESA'
	ELSE 
		PRINT 'MESMO NÚMERO DE MULHERES E HOMENS NA EMPRESA'

/* INSERINDO NOVO FUNCIONARIO */
INSERT INTO Funcionario (NOME,CPF,DataNascimento,Sexo,DataAdmissao,Salario,Email)
VALUES ('Luciana Soares', '12345678933','1980-05-05','F', '2017-01-05',3500.00, 'luciana.soares@empresa.com')