/*VERIFICAR NOME DOS ARQUIVOS MDF E LDF DO BACKUP*/
RESTORE FILELISTONLY FROM DISK ='D:\BACKUPS\COMPLETO\BACKUP_FULL_TSQL_CONSULTABD.BAK'

/* PRIMEIRO: RECUPERAR ULTIMO BACKUP FULL, COM A CLAUSULA NORECOVERY - O BANCO FICA INDISPONIVEL PARA UTILIZAÇÃO*/
RESTORE DATABASE ConsultaBDTeste
FROM DISK = N'D:\BACKUPS\COMPLETO\BACKUP_FULL_TSQL_CONSULTABD.BAK'
WITH
FILE = 1,
MOVE 'CONSULTABD' TO 'C:\PROGRAM FILES\MICROSOFT SQL SERVER\MSSQL11.MSSQLSERVER\MSSQL\DATA\CONSULTABDTESTE.MDF',
MOVE 'CONSULTABD_LOG' TO 'C:\PROGRAM FILES\MICROSOFT SQL
SERVER\MSSQL11.MSSQLSERVER\MSSQL\DATA\CONSULTABDTESTE_LOG.LDF',
NORECOVERY,
NOUNLOAD,
STATS = 10
GO

/*SEGUNDO: ESCOLHER QUAL BACKUP DIFERENCIAL SERÁ UTILIZADO*/
RESTORE DATABASE ConsultaBDTeste
FROM DISK = 'D:\BACKUPS\DIFERENCIAL\BKP_DIF1_CONSULTABD_MS.BAK'
WITH
NORECOVERY
GO

/*TERCEIRO: RESTAURAR BACKUPS DE LOG NA ORDEM QUE FORAM FEITOS*/
/* 1 BACKUP DE LOG - CONTEM AS 3 INSERTS/*
RESTORE LOG ConsultaBDTeste
FROM DISK = 'D:\BACKUPS\LOG\CONSULTABD_BKP_LOG_MS.TRN'
WITH NORECOVERY
GO

/*2 BACKUP DE LOG - CONTEM UM UPDATE*/
RESTORE LOG ConsultaBDTeste
FROM DISK = 'D:\BACKUPS\LOG\CONSULTABD_BKP_LOG_TSQL.TRN'
WITH NORECOVERY
GO

/*TORNANDO O BANCO DISPONIVEL PARA UTILIZAÇÃO*/
RESTORE DATABASE ConsultaBDTeste
WITH RECOVERY
GO