/*CRIANDO TRIGGER DE INSERT*/

CREATE TRIGGER TR_INSERT_CARGO 
ON CARGO
FOR INSERT
AS
BEGIN
		SELECT I.* FROM INSERTED I
		INNER JOIN CARGO C
		ON (I.CARGOID = C.CARGOID)
END

/* TESTANDO TRIGGER DE INSERT*/
INSERT INTO CARGO (NOME, ATIVIDADES,DEPARTID)
VALUES ('ESTAGIÁRIO DE TI', '', NULL);


/*CRIANDO TRIGGER DE UPDATE*/

CREATE TRIGGER TR_UPDATE_CARGO 
ON CARGO
FOR UPDATE
AS
BEGIN

/*ANTES DA ATUALIZAÇÃO*/
SELECT D.* FROM DELETED D
INNER JOIN CARGO C
ON (D.CARGOID = C.CARGOID)

/* DEPOIS DA ATUALIZAÇÃO*/
SELECT I.* FROM INSERTED I
INNER JOIN CARGO C
ON (I.CARGOID = C.CARGOID)

END

/*TESTANDO TRIGGER DE UPDATE*/
UPDATE CARGO
SET ATIVIDADES = 'AUXILIAR OS PROCESSOS DOS ANALISTAS DE TI E ADQUIRIR EXPERIENCIA PROFISSIONAL'
WHERE CARGOID = 10

/*CRIANDO TRIGGER DE DELETE*/
CREATE  TRIGGER TR_DELETE_CARGO 
ON CARGO
FOR DELETE
AS
BEGIN

/*REGISTRO DELETADO*/
PRINT 'REGISTRO EXCLUÍDO COM SUCESSO!!!'

END

/*TESTANDO TRIGGER DE UPDATE*/
DELETE FROM CARGO
WHERE CARGOID = 10