/* MINI_MUNDO_RH: */
IF DB_ID('MINI_MUNDO_RH') IS NOT NULL
BEGIN
	USE Master
	DROP DATABASE MINI_MUNDO_RH
END
-------------------------------------------------------------------------------
CREATE DATABASE MINI_MUNDO_RH
GO
-------------------------------------------------------------------------------
USE MINI_MUNDO_RH;
-------------------------------------------------------------------------------

CREATE TABLE PARENTESCO (
    CODIGO INT CONSTRAINT PK_PARENTESCO PRIMARY KEY IDENTITY(1,1),
    DESCRICAO VARCHAR(MAX) NOT NULL,
	DTCRIACAO DATE CONSTRAINT DFLT_CRIACAO_PARENTESCO DEFAULT (GETDATE()),
	DTALTERACAO DATE NULL
	
);

CREATE TABLE DEPARTAMENTO (
    CODIGO INT CONSTRAINT PK_DEPTO PRIMARY KEY IDENTITY(1,1),
    NOME VARCHAR(MAX) NOT NULL,
	DTCRIACAO DATE CONSTRAINT DFLT_CRIACAO_DEPARTAMENTO DEFAULT (GETDATE()),
	DTALTERACAO DATE NULL
);

CREATE TABLE SITUACAO (
    CODIGO INT CONSTRAINT PK_SITUACAO PRIMARY KEY IDENTITY(1,1),
    NOME VARCHAR(MAX) NOT NULL,
	DTCRIACAO DATE CONSTRAINT DFLT_CRIACAO_SITUACAO DEFAULT (GETDATE()),
	DTALTERACAO DATE NULL
); 

CREATE TABLE SALARIO (
    CODIGO INT CONSTRAINT PK_SALARIO PRIMARY KEY IDENTITY(1,1),
    VALOR MONEY,
	DTCRIACAO DATE CONSTRAINT DFLT_CRIACAO_SALARIO DEFAULT (GETDATE()),
	DTALTERACAO DATE NULL
);

CREATE TABLE FUNCAO (
    CODIGO INT CONSTRAINT PK_FUNCAO PRIMARY KEY IDENTITY(1,1),
    NOME VARCHAR(MAX) NOT NULL,
    DESCRICAO VARCHAR(MAX),
    CODSALARIO INT,
    FUNCAOCHEFIA INT,
	CONSTRAINT FK_FUNCAO_SALARIO FOREIGN KEY (CODSALARIO)
    REFERENCES SALARIO (CODIGO),
	CONSTRAINT FK_FUNCAO_CHEFIA FOREIGN KEY (FUNCAOCHEFIA)
    REFERENCES FUNCAO (CODIGO),
	DTCRIACAO DATE CONSTRAINT DFLT_CRIACAO_FUNCAO DEFAULT (GETDATE()),
	DTALTERACAO DATE NULL
);

CREATE TABLE PESSOA (
    CODIGO INT CONSTRAINT PK_PESSOA PRIMARY KEY IDENTITY(1,1),
    NOME VARCHAR(MAX) NOT NULL,
    CPF CHAR(11) UNIQUE NOT NULL CONSTRAINT CK_CPF CHECK  (CPF < 11),
    DTNASCIMENTO DATE NOT NULL,
    SEXO CHAR(1) CONSTRAINT CK_SEXO_PESSOA CHECK (SEXO='M' OR SEXO='F' OR SEXO='O'),
    ENDERECO VARCHAR(MAX) NULL,
    CIDADE VARCHAR(MAX) NULL,
    ESTADO VARCHAR(MAX) NULL,
    PAIS VARCHAR(MAX) NULL CONSTRAINT DEFAULT_PAIS DEFAULT ('BRASIL'),
    EMAIL VARCHAR(MAX) NULL,
    CELULAR VARCHAR(MAX) NULL,
    TEL_RESIDENCIAL VARCHAR(MAX) NULL,
	DTCRIACAO DATE CONSTRAINT DFLT_CRIACAO_PESSOA DEFAULT (GETDATE()),
	DTALTERACAO DATE NULL
);

CREATE TABLE FUNCIONARIO (
    MATRICULA INT CONSTRAINT PK_FUNCIONARIO PRIMARY KEY IDENTITY(1,1),
    DTADMISSAO DATE CONSTRAINT DEFAULT_ADMISSAO DEFAULT (GETDATE()) ,
    DTDEMISSAO DATE,
    SALARIO MONEY,
    CODPESSOA INT,
    CODDEPTO INT,
    CODSITUACAO INT,
    CODFUNCAO INT,
    CODCHEFE INT,
	CONSTRAINT FK_FUNCIONARIO_CHEFE FOREIGN KEY (CODCHEFE)
    REFERENCES FUNCIONARIO (MATRICULA),
	CONSTRAINT FK_FUNCIONARIO_PESSOA FOREIGN KEY (CODPESSOA)
    REFERENCES PESSOA (CODIGO),
	CONSTRAINT FK_FUNCIONARIO_FUNCAO FOREIGN KEY (CODFUNCAO)
    REFERENCES FUNCAO (CODIGO),
	CONSTRAINT FK_FUNCIONARIO_SITUACAO FOREIGN KEY (CODSITUACAO)
    REFERENCES SITUACAO (CODIGO),
	CONSTRAINT FK_FUNCIONARIO_DEPTO FOREIGN KEY (CODDEPTO)
    REFERENCES DEPARTAMENTO (CODIGO),
	DTCRIACAO DATE CONSTRAINT DFLT_CRIACAO_FUNCIONARIO DEFAULT (GETDATE()),
	DTALTERACAO DATE NULL
);

CREATE TABLE DEPENDENTES (
    CODIGO INT CONSTRAINT PK_DEPENDENTES PRIMARY KEY IDENTITY (1,1),
    CODMATRICULA INT,
    CODPARENTESCO INT,
    CODPESSOA INT,
	CONSTRAINT FK_DEPENTENTES_FUNCIONARIO FOREIGN KEY (CODMATRICULA)
    REFERENCES FUNCIONARIO (MATRICULA),
	CONSTRAINT FK_DEPENTENTES_PARENTESCO FOREIGN KEY (CODPARENTESCO)
    REFERENCES PARENTESCO (CODIGO),
	CONSTRAINT FK_DEPENTENTES_PESSOA FOREIGN KEY (CODPESSOA)
    REFERENCES PESSOA (CODIGO),
	DTCRIACAO DATE CONSTRAINT DFLT_CRIACAO_DEPENDENTES DEFAULT (GETDATE()),
	DTALTERACAO DATE NULL

);


CREATE TABLE HISTORICO_SITUACAO (
    CODMATRICULA INT,
    CODSITUACAO INT,
    PRIMARY KEY (CODSITUACAO, CODMATRICULA),
	CONSTRAINT FK_HIST_FUNCIONARIO_SITUACAO FOREIGN KEY (CODMATRICULA)
    REFERENCES FUNCIONARIO (MATRICULA),
	CONSTRAINT FK_HIST_SITUACAO_FUNCIONARIO FOREIGN KEY (CODSITUACAO)
    REFERENCES SITUACAO (CODIGO),
	DTCRIACAO DATE CONSTRAINT DFLT_CRIACAO_HISTSIT DEFAULT (GETDATE()),
	DTALTERACAO DATE NULL
);

CREATE TABLE HISTORICO_FUNCAO (
    CODMATRICULA INT,
    CODFUNCAO INT,
    SALARIO_ATUAL MONEY,
    PRIMARY KEY (CODMATRICULA, CODFUNCAO),
	CONSTRAINT FK_HIST_FUNCIONARIO_FUNCAO FOREIGN KEY (CODMATRICULA)
    REFERENCES FUNCIONARIO (MATRICULA),
	CONSTRAINT FK_HIST_FUNCAO_FUNCIONARIO FOREIGN KEY (CODFUNCAO)
    REFERENCES FUNCAO (CODIGO),
	DTCRIACAO DATE CONSTRAINT DFLT_CRIACAO_HISTFUNC DEFAULT (GETDATE()),
	DTALTERACAO DATE NULL
);
 