/*CONCAT*/
/*SELECT 'CONSULTA' + ' ' + 'BD' + ' ' +  2016*/

SELECT 'CONSULTA' + ' ' + 'BD' + ' ' +  CONVERT (VARCHAR (4), 2016) as 'SEM CONCAT'

SELECT CONCAT('CONSULTA',' BD', ' ', 2016) AS 'COM CONCAT'


/*FORMAT*/
DECLARE @DATA DATETIME 

SET @DATA = GETDATE();

SELECT FORMAT( @DATA, 'yyyy/MM/dd', 'en-US' ) AS 'MASCARA DATA US	'
SELECT FORMAT( @DATA, 'dd/MM/yyyy', 'PT-BR' ) AS 'MASCARA DATA BR'

SELECT FORMAT(12345678911,'000-000-000-00') AS 'MASCARA NUMERO';

SELECT FORMAT(25.25, 'C', 'en-us')  AS 'VALOR MOEDA US'
SELECT FORMAT(25.25, 'C', 'pt-br')  AS 'VALOR MOEDA BR'