CREATE DATABASE CONSULTABD;

USE CONSULTABD;

CREATE TABLE FUNCIONARIO
(MATRICULA INT PRIMARY KEY IDENTITY,
NOME VARCHAR(255) NOT NULL,
CPF CHAR(11) UNIQUE NOT NULL,
DTNASCIMENTO DATE NOT NULL,
ADMISSAO DATE DEFAULT (GETDATE()),
DEMISSAO DATE,
SEXO CHAR(1) CHECK (SEXO = 'M' OR SEXO = 'F' OR SEXO = 'O'),
STATUS_FUNC BIT CHECK (STATUS_FUNC = 1 OR STATUS_FUNC = 0),
CARGO VARCHAR(200),
CODIGO_CHEFE INT,
FOREIGN KEY (CODIGO_CHEFE) REFERENCES FUNCIONARIO (MATRICULA)
)


INSERT INTO FUNCIONARIO (NOME, CPF, DTNASCIMENTO, ADMISSAO, DEMISSAO, SEXO, STATUS_FUNC, CARGO, CODIGO_CHEFE)
VALUES ('JOAO', '12345678910', '1990-05-06', '2011-08-08', NULL, 'M', 1, 'GERENTE', NULL ),
	   ('MARIA', '12345678911', '1992-05-06', '2013-10-10', NULL, 'F', 1, 'ANALISTA DE RH', 1 ),
	   ('JOSE', '12345678912', '1995-05-06', '2014-01-15', NULL, 'O', 1, 'ASSISTENTE DE RH', 1 )
GO


SELECT 
	A1.NOME AS 'CHEFE', 
	A1.CARGO AS 'CARGO CHEFE', 
	A2.NOME AS 'FUNCIONARIO', 
	A2.CARGO AS 'CARGO FUNCIONARIO' 
FROM FUNCIONARIO A1
INNER JOIN FUNCIONARIO A2
ON (A1.MATRICULA = A2.CODIGO_CHEFE)