/*
SINTAXE:

SELECT coluna1, coluna2 FROM TABELA1
INTERSECT
SELECT coluna1, coluna2 FROM TABELA2

EX.: FAZER UMA CONSULTA QUE RETORNE OS PAÍSES QUE SÃO COMUNS ENTRE FUNCIONÁRIOS E CLIENTES.
*/

SELECT COUNTRY FROM HR.EMPLOYEES
INTERSECT
SELECT COUNTRY FROM SALES.CUSTOMERS