CREATE DATABASE EmpresaConsultaBD;
USE EmpresaConsultaBD;
GO

CREATE TABLE Departamento
(
DepartID INT CONSTRAINT PK_Depart PRIMARY KEY IDENTITY (1,1),
Nome VARCHAR(50)NOT NULL,
Orcamento DECIMAL (10,2) CONSTRAINT DF_Orcamento DEFAULT
20000
);

CREATE TABLE Cargo
(
CargoID INT CONSTRAINT PK_Cargo PRIMARY KEY IDENTITY (1,1),
Nome VARCHAR (50) NOT NULL,
Atividades NVARCHAR (MAX) NOT NULL,
DepartID INT CONSTRAINT FK_CargoDepart
FOREIGN KEY (DepartID) REFERENCES Departamento(DepartID)
);

CREATE TABLE Funcionario
(
FuncID INT CONSTRAINT PK_Func PRIMARY KEY IDENTITY (1,1),
Nome VARCHAR(200)NOT NULL,
CPF CHAR(11) CONSTRAINT UQ_CPF UNIQUE,
DataNascimento DATE NOT NULL,
Sexo CHAR(1)CONSTRAINT CK_Sexo
CHECK (Sexo ='M' OR Sexo='F'),
DataAdmissao DATE CONSTRAINT DF_Admissao DEFAULT GETDATE(),
DataDemissao DATE CONSTRAINT DF_Demissao DEFAULT NULL,
Salario DECIMAL(10,2),
Email VARCHAR (50),
Status bit CONSTRAINT DF_Status DEFAULT 1,
Supervisor INT CONSTRAINT DF_Supervisor DEFAULT NULL,
CargoID INT CONSTRAINT FK_FuncCargo
FOREIGN KEY(CargoID) REFERENCES Cargo(CargoID)
);