/*
SINTAXE:

SELECT coluna1, coluna2 FROM TABELA1
UNION [ALL]
SELECT coluna1, coluna2 FROM TABELA2

EX.: FAZER UMA CONSULTA QUE RETORNE OS FUNCIONÁRIOS QUE GANHAM MENOS OU IGUAL A 2000 E OS FUNCIONÁRIOS QUE GANHAM MAIOR OU IGUAL A 2000.

1 – COM UNION – A FUNCIONÁRIA JULIANA ALCANTRA APARECE EM AMBAS AS CONSULTAS POIS A MESMA TEM O SALARIO IGUAL A 2000. NO MOMENTO QUE UTILIZAMOS O UNION, ELE REMOVE AS DUPLICATAS DO RESULTADO DA CONSULTA.
*/
SELECT NOME, SALARIO  FROM FUNCIONARIO
WHERE SALARIO <= 2000

UNION

SELECT NOME, SALARIO FROM FUNCIONARIO
WHERE SALARIO >= 2000
ORDER BY NOME

 

/*
2 – COM UNION ALL- A FUNCIONÁRIA JULIANA ALCANTRA APARECE EM AMBAS AS CONSULTAS POIS A MESMA 
TEM O SALARIO IGUAL A 2000. QUANDO UTILIZAMOS O UNION ALL ELE NOS PERMITE RETORNAR DADOS DUPLICADOS NA CONSULTA.
*/
SELECT NOME, SALARIO  FROM FUNCIONARIO
WHERE SALARIO <= 2000

UNION ALL

SELECT NOME, SALARIO FROM FUNCIONARIO
WHERE SALARIO >= 2000
ORDER BY NOME