/*DECLARAMOS UMA VARIAVEL CHAMADA DATA E ATRIBUIMOS A DATA DO SISTEMA*/

DECLARE @DATA DATETIME = GETDATE();  

SELECT EOMONTH ( @DATA ) AS 'ULTIMO DIA DO MES';  /*SEM O PARAMETRO OPCIONAL*/
SELECT EOMONTH ( @DATA, 1 ) AS 'ULTIMO DIA DO MES SEGUINTE';   /*COM O PARAMETRO OPCIONAL*/
SELECT EOMONTH ( @DATA, -1 ) AS 'ULTIMO DIA DO MES ANTERIOR';  /*COM O PARAMETRO OPCIONAL*/