DBCC CHECKDB (CONSULTABD)

/*Verificano a base e retornando somente os erros*/
DBCC CHECKDB (CONSULTABD)
WITH ALL_ERRORMSGS, NO_INFOMSGS

/*reparando erros encontrados*/
ALTER DATABASE ConsultaBD SET SINGLE_USER
WITH ROLLBACK IMMEDIATE;
GO

DBCC CHECKDB(ConsultaBD, REPAIR_REBUILD)
WITH ALL_ERRORMSGS, NO_INFOMSGS