/*DUAS CONSULTAS DISTINTAS*/
SELECT * FROM FUNCIONARIO
WHERE SEXO = 'M'
AND DATADEMISSAO IS NOT NULL

SELECT * FROM FUNCIONARIO
WHERE  SEXO = 'F'
AND DATADEMISSAO IS NULL

/* COM UNION*/
SELECT * FROM FUNCIONARIO
WHERE SEXO = 'M'
AND DATADEMISSAO IS NOT NULL
UNION
SELECT * FROM FUNCIONARIO
WHERE  SEXO = 'F'
AND DATADEMISSAO IS NULL

/*UTILIZANDO ISOLAMENTO DE CONDIÇÕES*/
SELECT * 
FROM FUNCIONARIO
WHERE (SEXO = 'M'AND DATADEMISSAO IS NOT NULL)
OR (SEXO = 'F'AND DATADEMISSAO IS NULL)