BACKUP DATABASE CONSULTABD
TO DISK = N'D:\Backups\Completo\backup_full_TSQL_consultabd.bak'
WITH 
NOFORMAT,
INIT,
NAME = N'BACKUP FULL COM T-SQL',
SKIP,
NOREWIND,
NOUNLOAD,
STATS = 10,
CHECKSUM
GO