/* Criando procedure de INSERT*/

CREATE PROC SP_INSERT_FUNCIONARIO
(
@NOME VARCHAR(MAX),
@CPF CHAR(11),
@DT_NASC DATE,
@SEXO CHAR (1),
@DT_ADM DATE,
@DT_DEM DATE,
@SALARIO NUMERIC(18,2),
@EMAIL VARCHAR(50),
@STATUS INT,
@SUPERVISOR INT,
@CARGO INT
)
AS
BEGIN
		INSERT INTO FUNCIONARIO (NOME, CPF, DATANASCIMENTO, SEXO, DATAADMISSAO, DATADEMISSAO, SALARIO, EMAIL, STATUS, SUPERVISOR, CARGOID)
		VALUES (@NOME, @CPF, @DT_NASC,@SEXO,@DT_ADM,@DT_DEM,@SALARIO,@EMAIL,@STATUS,@SUPERVISOR,@CARGO)
END

/* INSERINDO FUNCIONARIO ATRAVES DA PROCEDURE*/
EXEC SP_INSERT_FUNCIONARIO 'Fernando Luiz', '12346789333' , '1990-05-12','M','2016-02-01',NULL,750.00, NULL, 1, NULL, NULL

SELECT * FROM Funcionario


-------------------------------------------
/* CRIANDO PROCEDURE PARA BUSCAR POR NOME*/
CREATE PROCEDURE SP_BUSCANDO_FUNC_POR_NOME
 (
 @NOME VARCHAR (200)
 )
AS
BEGIN
	SELECT * FROM VW_DADOS_FUNC V
	WHERE V.FUNCIONARIO LIKE '%' + @NOME + '%'
END

/*FAZENDO BUSCA NA VIEW ATRAVES DA PROCEDURE*/
EXECUTE  SP_BUSCANDO_FUNC_POR_NOME 'F'

select * from Cargo