BACKUP DATABASE CONSULTABD
TO DISK = N'D:\Backups\Diferencial\bkp_dif2_consultabd_tsql.bak'
WITH DIFFERENTIAL,
NOFORMAT,
INIT,
NAME = N'BACKUP DIFFERENTIAL COM T-SQL',
SKIP,
NOREWIND,
NOUNLOAD,
STATS = 10
GO